import {
  TrendingUp,
  Landmark,
  Receipt,
  Percent,
  CalendarDays,
  CaseSensitive,
  Braces,
  ImageIcon,
  FileText,
  QrCode,
  AlignLeft,
  Binary,
  PiggyBank,
  Shield,
  FileSpreadsheet,
  Briefcase,
  BarChart3,
  Ruler,
  ClipboardList,
  LineChart,
  CreditCard,
  Palette,
  Table,
  ScrollText,
  FileCode,
  Database,
  Coffee,
  ImageDown,
  FileStack,
  Archive,
  FilePen,
  Hash,
  Clock,
  Code2,
  KeyRound,
} from "lucide-react";

export const toolsData = [
  {
    name: "Salary Slip Generator",
    slug: "salary-slip-generator",
    description: "Generate professional salary slips with company logo, earnings, deductions and PDF download.",
    gradient: "from-violet-600 to-indigo-700",
    badge: "New",
    icon: ScrollText
  },
  {
    name: "SIP Calculator",
    slug: "sip-calculator",
    description: "Calculate mutual fund returns with step-up & inflation adjustment.",
    gradient: "from-blue-600 to-indigo-600",
    badge: "Popular",
    icon: TrendingUp
  },
  {
    name: "EMI Calculator",
    slug: "emi-calculator",
    description: "Plan your loan repayment with detailed amortization schedule.",
    gradient: "from-emerald-500 to-teal-600",
    badge: "Popular",
    icon: Landmark
  },
  {
    name: "GST Calculator",
    slug: "gst-calculator",
    description: "Quickly add or remove GST with standard tax slabs.",
    gradient: "from-amber-500 to-orange-600",
    badge: null,
    icon: Receipt
  },
  {
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Solve complex percentage math instantly.",
    gradient: "from-violet-500 to-purple-600",
    badge: null,
    icon: Percent
  },
  {
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Find out your exact age in years, months, and days.",
    gradient: "from-rose-500 to-pink-600",
    badge: "New",
    icon: CalendarDays
  },
  {
    name: "Text Case Converter",
    slug: "text-case-converter",
    description: "Convert text between upper, lower, title case and more.",
    gradient: "from-cyan-500 to-sky-600",
    badge: null,
    icon: CaseSensitive
  },
  {
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Beautify, minify, and validate JSON data instantly.",
    gradient: "from-slate-600 to-gray-800",
    badge: null,
    icon: Braces
  },
  {
    name: "Image Converter",
    slug: "image-converter",
    description: "Convert images between PNG, JPG, and WebP. Resize quality, download instantly.",
    gradient: "from-pink-500 to-rose-600",
    badge: "New",
    icon: ImageIcon
  },
  {
    name: "Markdown Converter",
    slug: "markdown-converter",
    description: "Write Markdown and export to PDF, Word DOC, or HTML with live preview.",
    gradient: "from-violet-500 to-purple-700",
    badge: "New",
    icon: FileText
  },
  {
    name: "QR Code Generator",
    slug: "qr-code-generator",
    description: "Generate QR codes for URLs, UPI IDs, phones, and more. Download as PNG.",
    gradient: "from-teal-500 to-emerald-600",
    badge: "New",
    icon: QrCode
  },
  {
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, characters, sentences. Get reading time and top keyword analysis.",
    gradient: "from-orange-500 to-amber-600",
    badge: "New",
    icon: AlignLeft
  },
  {
    name: "Base64 Tool",
    slug: "base64-tool",
    description: "Encode text or files to Base64, or decode Base64 strings back to plain text.",
    gradient: "from-slate-500 to-zinc-700",
    badge: "New",
    icon: Binary
  },
  {
    name: "FD Calculator",
    slug: "fd-calculator",
    description: "Calculate Fixed Deposit maturity & interest with SBI, HDFC, ICICI bank rate presets.",
    gradient: "from-green-500 to-emerald-700",
    badge: "New",
    icon: PiggyBank
  },
  {
    name: "PPF Calculator",
    slug: "ppf-calculator",
    description: "Calculate Public Provident Fund returns with year-by-year interest breakdown.",
    gradient: "from-sky-500 to-cyan-600",
    badge: "New",
    icon: Shield
  },
  {
    name: "Income Tax Calculator",
    slug: "income-tax-calculator",
    description: "Compare new vs old tax regime and calculate income tax for FY 2025-26.",
    gradient: "from-red-500 to-rose-700",
    badge: "New",
    icon: FileSpreadsheet
  },
  {
    name: "Salary / CTC Calculator",
    slug: "ctc-calculator",
    description: "Break down your CTC into in-hand salary with PF, HRA, and gratuity components.",
    gradient: "from-indigo-600 to-blue-800",
    badge: "New",
    icon: Briefcase
  },
  {
    name: "Compound Interest Calculator",
    slug: "compound-interest-calculator",
    description: "Calculate compound interest with daily, monthly, quarterly, and yearly compounding.",
    gradient: "from-purple-600 to-violet-800",
    badge: "New",
    icon: BarChart3
  },
  {
    name: "Unit Converter",
    slug: "unit-converter",
    description: "Convert weight, length, volume, temperature including Indian units like Tola and Maund.",
    gradient: "from-amber-400 to-orange-500",
    badge: "New",
    icon: Ruler
  },
  {
    name: "Invoice Generator",
    slug: "invoice-generator",
    description: "Create GST-ready invoices with CGST/SGST/IGST split and download as PDF.",
    gradient: "from-gray-700 to-slate-900",
    badge: "New",
    icon: ClipboardList
  },
  {
    name: "CAGR Calculator",
    slug: "cagr-calculator",
    description: "Calculate Compound Annual Growth Rate for investments or find future value at a given CAGR.",
    gradient: "from-lime-500 to-emerald-600",
    badge: "New",
    icon: LineChart
  },
  {
    name: "Loan Eligibility Calculator",
    slug: "loan-eligibility-calculator",
    description: "Find out your maximum loan amount based on salary, existing EMIs, tenure and FOIR.",
    gradient: "from-cyan-600 to-blue-700",
    badge: "New",
    icon: CreditCard
  },
  {
    name: "Color Converter",
    slug: "color-converter",
    description: "Convert colors between HEX, RGB and HSL with live preview, palette, and copy buttons.",
    gradient: "from-fuchsia-500 to-pink-600",
    badge: "New",
    icon: Palette
  },
  {
    name: "CSV ↔ JSON Converter",
    slug: "csv-json-converter",
    description: "Convert CSV to JSON or JSON to CSV instantly. Supports custom delimiters, file upload and preview.",
    gradient: "from-yellow-500 to-orange-500",
    badge: "New",
    icon: Table
  },
  {
    name: "XML ↔ JSON Converter",
    slug: "xml-json-converter",
    description: "Convert XML to JSON or JSON to XML instantly. Upload a file or paste your data.",
    gradient: "from-cyan-500 to-blue-600",
    badge: "New",
    icon: FileCode
  },
  {
    name: "XML ↔ CSV Converter",
    slug: "xml-csv-converter",
    description: "Convert XML to CSV or CSV to XML with file upload support and table preview.",
    gradient: "from-emerald-500 to-teal-600",
    badge: "New",
    icon: FileSpreadsheet
  },
  {
    name: "XML Formatter",
    slug: "xml-formatter",
    description: "Beautify, format and minify XML. Validate structure and pretty-print with custom indentation.",
    gradient: "from-orange-500 to-red-500",
    badge: "New",
    icon: FileCode
  },
  {
    name: "SQL Formatter",
    slug: "sql-formatter",
    description: "Format SQL queries for MySQL, PostgreSQL, SQLite and more. Supports uppercase keywords.",
    gradient: "from-blue-600 to-indigo-700",
    badge: "New",
    icon: Database
  },
  {
    name: "Java Formatter",
    slug: "java-formatter",
    description: "Beautify and format Java source code — auto-indent, clean spacing, file upload support.",
    gradient: "from-amber-600 to-orange-700",
    badge: "New",
    icon: Coffee
  },
  {
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Compress and resize images in your browser. Adjust quality, set max dimensions, convert format.",
    gradient: "from-pink-500 to-rose-600",
    badge: "New",
    icon: ImageDown
  },
  {
    name: "PDF Tools",
    slug: "pdf-tools",
    description: "Merge multiple PDFs, split PDF by page range, and compress PDF size — all in your browser.",
    gradient: "from-red-600 to-rose-700",
    badge: "New",
    icon: FileStack
  },
  {
    name: "ZIP Extractor",
    slug: "zip-extractor",
    description: "Extract and download files from ZIP archives online. Preview contents and download individually.",
    gradient: "from-slate-600 to-gray-800",
    badge: "New",
    icon: Archive
  },
  {
    name: "PDF Editor",
    slug: "pdf-editor",
    description: "Draw, annotate, add text, erase content, watermark and fill form fields — 100% in your browser.",
    gradient: "from-orange-600 to-red-700",
    badge: "New",
    icon: FilePen
  },
  {
    name: "Number Base Converter",
    slug: "number-base-converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal with bit visualization.",
    gradient: "from-violet-500 to-indigo-600",
    badge: "New",
    icon: Hash
  },
  {
    name: "Timestamp Converter",
    slug: "timestamp-converter",
    description: "Convert Unix epoch timestamps to human-readable dates and back, with timezone support.",
    gradient: "from-blue-500 to-cyan-600",
    badge: "New",
    icon: Clock
  },
  {
    name: "Regex Tester",
    slug: "regex-tester",
    description: "Test regular expressions with live match highlighting, flag toggles, and common Indian patterns.",
    gradient: "from-emerald-500 to-teal-600",
    badge: "New",
    icon: Code2
  },
  {
    name: "JWT Decoder",
    slug: "jwt-decoder",
    description: "Decode and inspect JSON Web Token headers, payloads, expiry, and algorithm — no secret needed.",
    gradient: "from-amber-500 to-orange-600",
    badge: "New",
    icon: KeyRound
  },
];

export const toolCategories: Record<string, { label: string; slugs: string[] }> = {
  finance: {
    label: "Finance & Investments",
    slugs: ["sip-calculator", "emi-calculator", "fd-calculator", "ppf-calculator", "compound-interest-calculator", "cagr-calculator", "loan-eligibility-calculator"],
  },
  tax: {
    label: "Tax & Payroll",
    slugs: ["gst-calculator", "income-tax-calculator", "ctc-calculator", "salary-slip-generator", "invoice-generator"],
  },
  developer: {
    label: "Developer Tools",
    slugs: ["json-formatter", "base64-tool", "number-base-converter", "timestamp-converter", "regex-tester", "jwt-decoder", "color-converter", "markdown-converter", "csv-json-converter", "xml-json-converter", "xml-csv-converter", "xml-formatter", "sql-formatter", "java-formatter"],
  },
  utility: {
    label: "Utility Tools",
    slugs: ["percentage-calculator", "age-calculator", "text-case-converter", "word-counter", "unit-converter", "qr-code-generator", "image-converter", "image-compressor", "pdf-tools", "pdf-editor", "zip-extractor"],
  },
};

export const faqs: Record<string, { q: string; a: string }[]> = {
  "sip-calculator": [
    { q: "What is a SIP?", a: "A Systematic Investment Plan (SIP) is a method of investing a fixed sum regularly in a mutual fund scheme, typically monthly." },
    { q: "What is Step-Up SIP?", a: "Step-Up SIP allows you to increase your SIP amount automatically by a fixed percentage every year, helping you invest more as your income grows." },
    { q: "Are SIP returns guaranteed?", a: "No, mutual fund returns depend on market performance and are not guaranteed. Past performance is not indicative of future results." },
    { q: "What is Lumpsum investment?", a: "A lumpsum investment is depositing the entire amount at once instead of spreading it over months. It's suited for those with a large amount available to invest." },
    { q: "Is SIP better than Lumpsum?", a: "SIP is generally better for salaried individuals as it averages out market volatility through rupee cost averaging. Lumpsum can outperform in a rising market." },
    { q: "What is a good SIP return rate to expect?", a: "Historically, diversified equity mutual funds in India have delivered 10–14% CAGR over 10+ year periods. For conservative estimates, use 10–12%." },
  ],
  "emi-calculator": [
    { q: "What does EMI stand for?", a: "EMI stands for Equated Monthly Installment — a fixed monthly payment made by a borrower to a lender consisting of both principal repayment and interest." },
    { q: "How is EMI calculated?", a: "EMI = P × r × (1+r)^n / ((1+r)^n - 1), where P is principal, r is monthly interest rate (annual rate ÷ 12 ÷ 100), and n is number of months." },
    { q: "Does EMI change during the loan tenure?", a: "For fixed-rate loans, the EMI remains constant throughout. For floating-rate loans, it may change when the benchmark rate (like repo rate) changes." },
    { q: "What is an amortization schedule?", a: "An amortization schedule is a complete table of periodic loan payments showing how each EMI is split between principal repayment and interest over time." },
    { q: "Is interest calculated on the original or outstanding principal?", a: "Interest is calculated on the outstanding (reducing) balance. So the interest component decreases over time while the principal component increases — this is reducing balance method." },
    { q: "How can I reduce my total interest payment?", a: "Pay part-prepayments when possible, choose a shorter tenure if EMI is affordable, negotiate a lower interest rate, or refinance when rates drop." },
  ],
  "gst-calculator": [
    { q: "What is GST?", a: "GST (Goods and Services Tax) is a unified indirect tax in India that replaced VAT, service tax, and excise duty. It is levied at each stage of the supply chain." },
    { q: "What are the GST slabs in India?", a: "India has four main GST slabs: 5% (essential goods like packaged food), 12% (processed food, computers), 18% (most services and electronics), and 28% (luxury/sin goods like cars, tobacco). A 0% slab covers exempted items." },
    { q: "What is the difference between CGST, SGST, and IGST?", a: "For intra-state transactions, GST is split equally into CGST (Central GST) and SGST (State GST). For inter-state transactions, a single IGST at the full GST rate is levied." },
    { q: "How do I calculate GST on a price?", a: "To add GST: multiply price by (1 + GST%/100). To remove GST from an inclusive price: divide by (1 + GST%/100). For example, to remove 18% GST from ₹118: ₹118 / 1.18 = ₹100." },
    { q: "Who needs to register for GST?", a: "Businesses with annual turnover exceeding ₹20 lakh (₹10 lakh for special category states) must register for GST. E-commerce sellers must register regardless of turnover." },
    { q: "What is the GST composition scheme?", a: "The composition scheme allows small businesses (turnover up to ₹1.5 crore) to pay GST at a flat rate (1-6%) without maintaining detailed invoices. They cannot claim input tax credit." },
  ],
  "fd-calculator": [
    { q: "What is a Fixed Deposit?", a: "A Fixed Deposit (FD) is a financial instrument where you deposit a lump sum with a bank for a fixed period at a predetermined interest rate, offering guaranteed returns unlike market-linked investments." },
    { q: "How is FD interest calculated?", a: "FD uses compound interest formula: A = P × (1 + r/n)^(nt), where P is principal, r is annual rate, n is compounding frequency per year, and t is time in years." },
    { q: "What is TDS on FD interest?", a: "Banks deduct TDS at 10% if your FD interest income exceeds ₹40,000 per year (₹50,000 for senior citizens). Submit Form 15G/15H if your total income is below the taxable limit to avoid TDS." },
    { q: "Can I withdraw FD before maturity?", a: "Yes, you can break an FD prematurely. Most banks charge a penalty of 0.5–1% on the applicable interest rate, which reduces your actual earnings." },
    { q: "Are FD returns taxable?", a: "Yes, FD interest is fully taxable under 'Income from Other Sources' at your applicable income tax slab rate. This makes high-income individuals prefer debt mutual funds for better post-tax returns." },
    { q: "Which bank offers the highest FD rate?", a: "Small finance banks and NBFCs typically offer higher FD rates (7–9%) than large banks. Our calculator includes preset rates for SBI, HDFC, and ICICI. Always verify current rates on the bank's website." },
  ],
  "ppf-calculator": [
    { q: "What is PPF?", a: "Public Provident Fund (PPF) is a long-term, government-backed savings scheme in India with a 15-year lock-in period, offering guaranteed tax-free returns backed by the sovereign." },
    { q: "What is the current PPF interest rate?", a: "The PPF interest rate is set by the Government of India each quarter. As of FY 2025-26, it is 7.1% per annum, compounded annually." },
    { q: "Is PPF interest tax-free?", a: "Yes, PPF has EEE (Exempt-Exempt-Exempt) tax status: contributions up to ₹1.5 lakh qualify for Section 80C deduction, interest earned is tax-free, and maturity proceeds are tax-free." },
    { q: "What is the minimum and maximum PPF deposit?", a: "Minimum deposit is ₹500 per year (account becomes inactive if you miss a year). Maximum is ₹1.5 lakh per financial year. Deposits can be made in up to 12 installments." },
    { q: "Can I take a loan against PPF?", a: "Yes, you can take a loan of up to 25% of the balance at the end of 2nd preceding year, between the 3rd and 6th financial year of the account, at 1% above PPF rate." },
    { q: "Can I extend PPF beyond 15 years?", a: "Yes, after 15 years you can extend in blocks of 5 years, either with or without contributions. Without contributions, the balance continues earning interest." },
  ],
  "income-tax-calculator": [
    { q: "What is the difference between old and new tax regime?", a: "Old regime allows many deductions (HRA, 80C, 80D, LTA etc.) but has higher slab rates. New regime offers lower slab rates but disallows most deductions except the standard deduction." },
    { q: "Which tax regime is better for me?", a: "If your total eligible deductions exceed ~₹3.75 lakh (₹50K standard + ₹1.5L 80C + ₹25K 80D + other), old regime usually saves more tax. New regime benefits those with fewer deductions." },
    { q: "What is standard deduction for salaried employees?", a: "For FY 2025-26, the standard deduction is ₹75,000 under the new tax regime and ₹50,000 under the old tax regime for salaried individuals and pensioners." },
    { q: "When is the income tax return due date?", a: "For individuals (non-audit cases), the ITR due date is July 31 of the assessment year. For example, for FY 2025-26, the due date is July 31, 2026." },
    { q: "What is TDS?", a: "Tax Deducted at Source (TDS) is tax deducted by the payer at the time of making payments like salary, interest, rent, or professional fees, and deposited with the government on your behalf." },
    { q: "What is surcharge on income tax?", a: "Surcharge is an additional tax levied on higher incomes: 10% surcharge on income above ₹50 lakh, 15% above ₹1 crore, 25% above ₹2 crore, and 37% above ₹5 crore (capped at 25% for new regime)." },
  ],
  "ctc-calculator": [
    { q: "What is CTC?", a: "Cost to Company (CTC) is the total annual expense an employer incurs for an employee, including basic salary, allowances, PF contributions, gratuity, insurance, and other benefits." },
    { q: "What is in-hand salary?", a: "In-hand (take-home) salary is the amount credited to your bank account after all deductions — employee PF contribution, professional tax, TDS, ESIC, etc. — are subtracted from your gross salary." },
    { q: "How is HRA exemption calculated?", a: "HRA exemption is the minimum of: actual HRA received; 50% of basic salary for metro cities (40% for non-metro); or rent paid minus 10% of basic salary. Only the minimum of these three is tax-free." },
    { q: "What is the employee PF contribution?", a: "Employees contribute 12% of basic salary + DA to EPF. Employer also contributes 12%, of which 8.33% goes to EPS (Employee Pension Scheme) and 3.67% to EPF." },
    { q: "What is gratuity and when is it paid?", a: "Gratuity is a lump-sum payment by an employer to an employee who has completed at least 5 years of continuous service. Gratuity = (Last drawn salary × years served × 15) / 26." },
    { q: "What are metro cities for HRA purposes?", a: "For HRA exemption, metro cities are: Delhi, Mumbai, Kolkata, and Chennai. All other cities are classified as non-metro, attracting 40% HRA exemption (vs 50% for metros)." },
  ],
  "compound-interest-calculator": [
    { q: "What is compound interest?", a: "Compound interest is interest calculated on both the initial principal and all previously accumulated interest, causing the investment to grow exponentially rather than linearly." },
    { q: "How often should interest compound for best returns?", a: "More frequent compounding yields higher returns. Daily > Monthly > Quarterly > Half-yearly > Annually. A 10% annual rate compounded daily yields ~10.52% effective annual rate." },
    { q: "What is the Rule of 72?", a: "The Rule of 72 estimates how long it takes to double your investment — divide 72 by the annual interest rate. At 8% per year, money doubles in approximately 72/8 = 9 years." },
    { q: "How does compound interest differ from simple interest?", a: "Simple interest is calculated only on the original principal. Compound interest is calculated on principal plus accumulated interest, making it grow much faster over time." },
    { q: "What is the effective annual rate (EAR)?", a: "EAR is the actual annual return accounting for compounding. Formula: EAR = (1 + r/n)^n - 1, where r is nominal annual rate and n is compounding periods per year." },
    { q: "Where is compound interest applied in real life?", a: "Compound interest applies to savings accounts, FDs, mutual funds, PPF, EPF, and mortgages. It works in your favor as an investor and against you as a borrower." },
  ],
  "cagr-calculator": [
    { q: "What is CAGR?", a: "Compound Annual Growth Rate (CAGR) is the mean annual growth rate of an investment over a period, assuming profits are reinvested at year-end. It's the single rate that would take you from start to end value." },
    { q: "How is CAGR calculated?", a: "CAGR = (Ending Value / Beginning Value)^(1/Years) - 1. Example: ₹1 lakh growing to ₹2 lakh in 5 years → CAGR = (2/1)^(0.2) - 1 ≈ 14.87% per year." },
    { q: "What is a good CAGR for investments?", a: "For equity mutual funds in India, 12–15% CAGR over 10+ years is considered strong. Nifty 50 has delivered ~11–13% CAGR over 20 years. FDs offer 6–7.5% CAGR." },
    { q: "What is the difference between CAGR and absolute return?", a: "Absolute return is the total percentage gain regardless of time period. CAGR normalizes this across years for comparison. A 100% absolute return over 10 years is only ~7.2% CAGR." },
    { q: "Can CAGR be negative?", a: "Yes. If the ending value is less than the starting value, CAGR is negative — indicating an average annual loss. This is common for poorly performing investments." },
  ],
  "loan-eligibility-calculator": [
    { q: "How is loan eligibility calculated?", a: "Banks typically allow a maximum EMI of 40–50% of your net monthly income (Fixed Obligations to Income Ratio or FOIR). Maximum loan = permissible EMI × [(1 - (1+r)^-n) / r], where r is monthly rate." },
    { q: "What is FOIR?", a: "Fixed Obligation to Income Ratio (FOIR) is the percentage of monthly income already committed to existing EMIs. Most banks cap total FOIR (including new loan) at 50–55%." },
    { q: "How do existing EMIs affect loan eligibility?", a: "Existing EMIs directly reduce the income available for new loan repayment. If you earn ₹1 lakh and already pay ₹30K EMI, only ₹20K (50% limit) is available for new loan EMI, significantly reducing eligibility." },
    { q: "How can I improve my loan eligibility?", a: "Add an earning co-applicant (spouse), clear existing debts, choose a longer repayment tenure, show additional income sources, or improve your CIBIL score to 750+." },
    { q: "What CIBIL score is needed for a home loan?", a: "Most banks require a CIBIL score of 750+ for home loans. Scores above 800 often get preferential interest rates. Below 650 typically results in rejection." },
  ],
  "percentage-calculator": [
    { q: "How do I find what percentage one number is of another?", a: "Divide the part by the whole and multiply by 100. Example: 25 is what % of 80? = (25 ÷ 80) × 100 = 31.25%." },
    { q: "How do I calculate percentage increase?", a: "% Increase = [(New Value - Old Value) / Old Value] × 100. Example: price goes from ₹100 to ₹120 → increase = (20/100) × 100 = 20%." },
    { q: "How do I find a percentage of a number?", a: "Multiply the number by (percentage ÷ 100). Example: 15% of ₹200 = 200 × 0.15 = ₹30." },
    { q: "How do I reverse a percentage to find the original price?", a: "Original price = Discounted price ÷ (1 - discount%/100). Example: if ₹85 is the price after 15% discount, original = 85 ÷ 0.85 = ₹100." },
    { q: "What is the difference between percentage points and percentage?", a: "Percentage points are the arithmetic difference between two percentages. If interest rises from 5% to 8%, that's 3 percentage points — but a 60% relative increase in the rate." },
  ],
  "age-calculator": [
    { q: "How is exact age calculated?", a: "Exact age is calculated by counting completed years, months, and days from your birth date to the target date, accounting for leap years and the varying number of days in each month." },
    { q: "Why is knowing exact age important in India?", a: "Exact age determines eligibility for voting (18+), driving license (18+), retirement (58-60), EPF withdrawal, senior citizen benefits, and education admissions cut-off dates." },
    { q: "What is the legal age for different milestones in India?", a: "Voting and driving: 18 years; Marriage: 18 for women, 21 for men (proposed 21 for all); EPF withdrawal without penalty: 58 years; Senior citizen tax benefits: 60 years; Super senior citizen: 80 years." },
    { q: "How to calculate age difference between two people?", a: "Subtract the earlier birth date from the later one. Our calculator handles this automatically and shows the difference in years, months, and days." },
    { q: "Does the age calculator account for leap years?", a: "Yes, our age calculator correctly handles February 29 birthdays and leap years in the date range for accurate results." },
  ],
  "unit-converter": [
    { q: "What Indian units are supported?", a: "Our unit converter supports traditional Indian units including Tola (gold measurement = 11.6638g), Maund, Ser, Ratti, Bigha (land measurement), Katha, and Gunta." },
    { q: "How many grams is 1 Tola?", a: "1 Tola = 11.6638 grams. This unit is widely used in India for measuring gold jewelry and precious metals in the bullion market." },
    { q: "How many square feet is 1 Bigha?", a: "1 Bigha varies significantly by state. It ranges from 1,333 sq ft (Himachal Pradesh) to 27,000 sq ft (Uttar Pradesh). Our converter uses standard conversions for each state." },
    { q: "How do I convert Celsius to Fahrenheit?", a: "Multiply by 9/5 then add 32. Formula: °F = (°C × 9/5) + 32. Example: 37°C (body temperature) = (37 × 1.8) + 32 = 98.6°F." },
    { q: "How many kilometers in a mile?", a: "1 mile = 1.60934 kilometers. Conversely, 1 km = 0.62137 miles. Road distances in India are in km; US/UK use miles." },
  ],
  "json-formatter": [
    { q: "What is JSON?", a: "JSON (JavaScript Object Notation) is a lightweight, text-based data format for storing and transmitting structured data. It uses key-value pairs and supports strings, numbers, booleans, arrays, and objects." },
    { q: "What is the difference between prettified and minified JSON?", a: "Prettified JSON has indentation and line breaks for human readability. Minified JSON strips all whitespace to reduce file size for network transmission, saving 20–30% bandwidth." },
    { q: "How do I validate JSON?", a: "Valid JSON requires double quotes around all string keys and values, no trailing commas, correct nesting of brackets, and proper data types. Our formatter highlights errors in real time." },
    { q: "What are common JSON errors?", a: "Common errors: single quotes instead of double quotes, trailing commas after the last item, unquoted keys, using undefined or NaN (not valid JSON), and mismatched brackets." },
    { q: "Can I convert JSON to CSV?", a: "Yes! Use our CSV ↔ JSON Converter tool to convert JSON arrays to CSV format and back, with support for nested objects and custom delimiters." },
  ],
  "qr-code-generator": [
    { q: "What types of QR codes can I generate?", a: "Generate QR codes for URLs (website links), UPI payment IDs, phone numbers (auto-dial), SMS messages, email addresses (mailto), and plain text — all for free." },
    { q: "What is a UPI QR code?", a: "A UPI QR code encodes a UPI Virtual Payment Address (VPA) like yourname@upi. When scanned with PhonePe, Google Pay, Paytm, or any UPI app, it pre-fills the recipient for instant payment." },
    { q: "What format should I download QR codes in?", a: "Download as PNG for websites and digital use. For printing on business cards or banners, use a higher error correction level (H) so the code scans even if partially damaged." },
    { q: "What is QR code error correction?", a: "Error correction allows a QR code to be scanned even when 7–30% of it is damaged or obscured. Higher levels (M, Q, H) are better for printed QR codes in physical environments." },
    { q: "Are the QR codes generated here free to use commercially?", a: "Yes, completely free with no watermark, no account required, and no restrictions on commercial use." },
  ],
  "word-counter": [
    { q: "What is the ideal word count for an SEO blog post?", a: "1,500–2,500 words typically perform best for competitive keywords. Informational pages often rank well with 800–1,500 words. Quality and relevance matter more than hitting a specific count." },
    { q: "How is reading time calculated?", a: "Reading time is estimated based on an average reading speed of 200–250 words per minute. A 1,000-word article takes approximately 4–5 minutes to read." },
    { q: "Does word count include headings and lists?", a: "Yes, all visible text including headings, bullet points, captions, and body text is counted." },
    { q: "What is the character limit for Twitter/X and Instagram?", a: "Twitter/X allows 280 characters per post. Instagram captions allow up to 2,200 characters. Our counter helps you stay within these limits." },
    { q: "What are keyword density and keyword frequency?", a: "Keyword frequency is how many times a word appears. Keyword density is frequency as a percentage of total words. Our top keywords section shows the most frequent words in your text." },
  ],
  "base64-tool": [
    { q: "What is Base64 encoding?", a: "Base64 is a binary-to-text encoding scheme that converts any binary data (images, files, binary strings) into a string of 64 printable ASCII characters, safe for text-based transport." },
    { q: "Why is Base64 used?", a: "Common uses: embedding images directly in HTML/CSS as data URIs, encoding email attachments (MIME), storing binary data in JSON, and transmitting binary data in URLs or APIs." },
    { q: "Does Base64 encoding increase file size?", a: "Yes, Base64 increases data size by approximately 33% because every 3 bytes of data becomes 4 characters. This is the trade-off for text compatibility." },
    { q: "Is Base64 the same as encryption?", a: "No. Base64 is encoding, not encryption. It only converts format — anyone can decode it without any key. Never use Base64 for security purposes." },
    { q: "What is the difference between Base64 and Base64 URL?", a: "Standard Base64 uses + and / which are not URL-safe. Base64 URL encoding replaces + with - and / with _, making it safe for use in URLs and JWT tokens." },
  ],
  "text-case-converter": [
    { q: "What is camelCase?", a: "camelCase writes compound words without spaces, with each word after the first capitalized. Used for variable and function names in JavaScript and Java: e.g., userFirstName." },
    { q: "What is snake_case?", a: "snake_case separates words with underscores in lowercase. Commonly used in Python variable names, database column names, and file names: e.g., user_first_name." },
    { q: "What is PascalCase?", a: "PascalCase capitalizes the first letter of every word with no separators. Used for class and component names in Java, C#, and React: e.g., UserFirstName." },
    { q: "What is kebab-case?", a: "kebab-case uses hyphens between lowercase words. Commonly used in CSS class names, HTML attributes, and URL slugs: e.g., user-first-name." },
    { q: "What is Title Case?", a: "Title Case capitalizes the first letter of each major word. Used in article headings, book titles, and proper nouns. Minor words like 'and', 'the', 'of' are typically lowercase." },
    { q: "What is SCREAMING_SNAKE_CASE?", a: "SCREAMING_SNAKE_CASE is all uppercase with underscores. Used for constants in many programming languages: e.g., MAX_RETRY_ATTEMPTS." },
  ],
  "salary-slip-generator": [
    { q: "What is a salary slip?", a: "A salary slip is an official document issued by an employer each month detailing an employee's earnings (basic, HRA, allowances) and deductions (PF, TDS, professional tax), along with net take-home pay." },
    { q: "Is a salary slip legally mandatory in India?", a: "While not explicitly mandated by a central law for all employers, salary slips are required by most labor laws for maintaining records. They are essential for loan applications, visa processing, and ITR filing." },
    { q: "What are the main components of a salary slip?", a: "Earnings: Basic salary, HRA, Conveyance allowance, Medical allowance, Special allowance. Deductions: Employee PF (12% of basic), TDS, Professional tax, ESIC. Net pay = Gross earnings minus total deductions." },
    { q: "How is basic salary typically set?", a: "Basic salary is usually 40–50% of CTC. HRA is 40–50% of basic salary (40% for non-metro, 50% for metro cities). Higher basic means higher PF deduction but also better HRA exemption." },
    { q: "Can a salary slip be used as proof of income?", a: "Yes, salary slips are widely accepted as income proof for home loans, personal loans, credit cards, rent agreements, and visa applications." },
  ],
  "invoice-generator": [
    { q: "What makes a GST invoice legally valid in India?", a: "A valid GST invoice must include: supplier name, address, and GSTIN; buyer details; unique serial invoice number; date; HSN/SAC code; item description with quantity and rate; taxable value; applicable GST (CGST+SGST or IGST); and total amount." },
    { q: "What is the difference between CGST+SGST and IGST on invoices?", a: "For intra-state supply (buyer and seller in same state), use CGST + SGST each at half the GST rate. For inter-state supply, use IGST at the full GST rate." },
    { q: "What is an E-Invoice?", a: "E-Invoicing is mandatory for GST-registered businesses with turnover above ₹5 crore. It involves generating an Invoice Reference Number (IRN) from the GST portal to validate each invoice digitally." },
    { q: "What is HSN code?", a: "Harmonised System of Nomenclature (HSN) code classifies goods for GST purposes. Businesses with turnover over ₹5 crore must use 6-digit HSN codes; others use 4-digit codes." },
    { q: "What is a Debit Note and Credit Note?", a: "A Debit Note increases the taxable value of a supply (issued when you charge more than invoiced). A Credit Note reduces it (issued for returns or overcharging). Both must be reported in GST returns." },
  ],
  "number-base-converter": [
    { q: "What is binary (base-2)?", a: "Binary is the base-2 numeral system using only 0 and 1. It is the fundamental language of computers, where each digit represents a power of 2 and maps directly to electronic on/off states." },
    { q: "What is hexadecimal (base-16)?", a: "Hexadecimal uses digits 0–9 and letters A–F to represent values 0–15. It is widely used in programming for representing memory addresses, HTML color codes (#FF6200), and binary data compactly." },
    { q: "How do I convert decimal to binary?", a: "Repeatedly divide the number by 2 and record the remainders. Read remainders from bottom to top. Example: 13 ÷ 2 = 6 R1, 6 ÷ 2 = 3 R0, 3 ÷ 2 = 1 R1, 1 ÷ 2 = 0 R1 → 1101 in binary." },
    { q: "Why do computers use binary?", a: "Digital circuits operate on two stable voltage states (high/low, on/off), which naturally represent 1 and 0. Binary arithmetic is implemented efficiently using logic gates in hardware." },
    { q: "What is an octal number?", a: "Octal is base-8, using digits 0–7. It was historically used in computing because 3 binary bits represent exactly one octal digit. It's still used in Unix file permissions (chmod 755)." },
  ],
  "timestamp-converter": [
    { q: "What is a Unix timestamp?", a: "A Unix timestamp (epoch time) is the number of seconds elapsed since January 1, 1970, at 00:00:00 UTC. It is timezone-independent and universally used in programming to represent moments in time." },
    { q: "What is the current Unix timestamp?", a: "The current Unix timestamp changes every second. Our live display shows the exact current epoch time. As of mid-2025, it is approximately 1,750,000,000." },
    { q: "How do I convert Unix timestamp to IST?", a: "Add 5 hours and 30 minutes (19,800 seconds) to the UTC time. IST is UTC+5:30. Our converter handles this automatically and also shows UTC, ISO 8601, and relative time." },
    { q: "What is the Y2K38 problem?", a: "32-bit signed Unix timestamps will overflow (wrap to 1901) on January 19, 2038 at 03:14:07 UTC. Modern 64-bit systems won't face this issue for billions of years." },
    { q: "What is ISO 8601 date format?", a: "ISO 8601 is an international standard for date-time representation: YYYY-MM-DDTHH:MM:SSZ. Example: 2025-06-24T10:30:00Z. The Z indicates UTC timezone." },
  ],
  "regex-tester": [
    { q: "What is a regular expression (regex)?", a: "A regular expression is a sequence of characters that defines a search pattern. It's used for string matching, validation (email, phone number), text extraction, and find-and-replace operations in programming." },
    { q: "What does the global (g) flag do?", a: "The global flag makes the regex engine find all matches in the text instead of stopping after the first match. Without it, only the first occurrence is returned." },
    { q: "How do I validate an Indian mobile number with regex?", a: "Use the pattern ^[6-9]\\d{9}$ — it matches 10-digit Indian mobile numbers starting with 6, 7, 8, or 9 (the valid prefixes for Indian mobile numbers)." },
    { q: "What is a capture group?", a: "A capture group (enclosed in parentheses) captures part of the matched string for reuse. Example: (\\d{4})-(\\d{2})-(\\d{2}) captures year, month, and day separately from a date string." },
    { q: "What do ^ and $ mean in regex?", a: "^ matches the start of the string (or line in multiline mode). $ matches the end. Together, they ensure the entire string must match the pattern, not just a substring." },
    { q: "How do I validate a PAN card number with regex?", a: "Use ^[A-Z]{5}[0-9]{4}[A-Z]{1}$ — it matches the PAN format: 5 uppercase letters, 4 digits, 1 uppercase letter. Example: ABCDE1234F." },
  ],
  "jwt-decoder": [
    { q: "What is a JWT?", a: "A JSON Web Token (JWT) is a compact, URL-safe string representing claims between two parties. It consists of three base64url-encoded parts separated by dots: Header.Payload.Signature." },
    { q: "Is it safe to decode a JWT online?", a: "Only decode test or non-sensitive tokens publicly. Never paste real user session tokens, auth tokens, or JWTs containing sensitive data into any online tool, including ours." },
    { q: "What is the JWT 'exp' claim?", a: "The 'exp' (expiration time) claim is a Unix timestamp after which the token must not be accepted. Our decoder clearly shows whether the token is currently valid or expired." },
    { q: "What algorithms do JWTs use?", a: "Common algorithms: HS256 (HMAC-SHA256, symmetric key), RS256 (RSA with public/private key pair), ES256 (ECDSA). The algorithm is specified in the 'alg' field of the JWT header." },
    { q: "Can I decode a JWT without the secret key?", a: "Yes. The header and payload are only base64url-encoded, not encrypted — anyone can decode and read them. The secret key is only needed to verify the signature's authenticity." },
    { q: "What is the difference between JWT and a session token?", a: "Session tokens are opaque random strings; the server stores session data. JWTs are self-contained — the server encodes data into the token itself and doesn't need to store it, enabling stateless authentication." },
  ],
  "markdown-converter": [
    { q: "What is Markdown?", a: "Markdown is a lightweight markup language with plain text formatting syntax. Created by John Gruber in 2004, it converts to HTML and is widely used for READMEs, documentation, blogs, and content management." },
    { q: "How do I create a table in Markdown?", a: "Use pipes and hyphens: | Header 1 | Header 2 | on the first line, | --- | --- | on the second, then data rows. Columns are separated by pipe characters." },
    { q: "Can I export Markdown to PDF?", a: "Yes, our Markdown Converter lets you export to PDF, Word DOCX, or HTML with a live preview. The PDF export formats your document with proper typography and styling." },
    { q: "What is the difference between Markdown and Rich Text?", a: "Markdown uses plain text with special characters for formatting (# for heading, ** for bold). Rich Text (RTF) stores formatting as metadata. Markdown is more portable and version-control friendly." },
  ],
  "color-converter": [
    { q: "What is the HEX color format?", a: "HEX is a 6-character hexadecimal code prefixed with # used in web design. Each pair of characters represents Red, Green, Blue (00–FF). Example: #FF6200 is orange." },
    { q: "What is RGB color?", a: "RGB specifies color by Red, Green, Blue intensity (0–255 each). rgb(255, 98, 0) is equivalent to #FF6200. Used in CSS, image editing, and screen displays." },
    { q: "What is HSL color?", a: "HSL represents color as Hue (0–360°), Saturation (0–100%), and Lightness (0–100%). It is more intuitive for adjusting color shades and tints than RGB or HEX." },
    { q: "Why do colors look different on screen vs print?", a: "Screens use additive RGB color (light-based). Printers use subtractive CMYK color (ink-based). Converting between them may shift colors, which is why screen designs look different when printed." },
  ],
  "image-converter": [
    { q: "What image formats are supported?", a: "You can convert between PNG, JPG/JPEG, and WebP formats. PNG is lossless and supports transparency; JPG is best for photos; WebP offers superior compression for web use." },
    { q: "Does converting to JPG lose quality?", a: "Yes, JPG uses lossy compression. Each conversion to JPG discards some data. Use the quality slider (80–90%) for a good balance between file size and visual quality." },
    { q: "What is WebP and why should I use it?", a: "WebP is a modern image format by Google that offers 25–35% smaller file sizes than JPG at equivalent quality. It is supported by all modern browsers and ideal for web performance." },
    { q: "Is image conversion done on my device?", a: "Yes, all conversion happens locally in your browser using the Canvas API. Your images are never uploaded to any server, ensuring complete privacy." },
    { q: "Can I convert multiple images at once?", a: "Our tool processes images one at a time. Upload, convert, and download each image individually for precise control over quality and format settings." },
  ],
  "image-compressor": [
    { q: "How does image compression work?", a: "The tool uses the browser's Canvas API to re-encode images at a lower quality level, reducing file size while maintaining acceptable visual quality. No upload to any server occurs." },
    { q: "What quality setting should I use?", a: "For web images, 75–85% quality is the sweet spot — typically 60–80% smaller files with minimal visible quality loss. For print or archival, use 90%+." },
    { q: "Can I resize images while compressing?", a: "Yes. Set a maximum width or height to resize the image proportionally while compressing. This is useful for reducing both dimensions and file size together." },
    { q: "What is the maximum file size supported?", a: "There is no hard server limit since processing is done in-browser. However, very large images (50MB+) may slow down the browser depending on your device's RAM." },
    { q: "Does compression affect transparency (PNG alpha)?", a: "Converting PNG to JPG removes transparency (replaces with white). To preserve transparency, keep the output format as PNG — though PNG compression is lossless so file size reduction is limited." },
  ],
  "pdf-tools": [
    { q: "Are my PDFs uploaded to a server?", a: "No. All PDF processing (merge, split, compress) is done entirely in your browser using PDF.js and pdf-lib. Your documents never leave your device." },
    { q: "Is there a file size limit for PDFs?", a: "Since processing is local, the limit depends on your device's memory. PDFs up to 100MB typically work fine. Very large PDFs may slow the browser on older devices." },
    { q: "Can I merge password-protected PDFs?", a: "Password-protected PDFs cannot be processed until unlocked. Remove the password protection from the PDF first using Adobe Acrobat or a similar tool." },
    { q: "How does PDF compression work here?", a: "Our in-browser compression re-encodes the PDF using pdf-lib, which strips redundant metadata and compresses streams. Results vary — text-heavy PDFs compress less than image-heavy ones." },
    { q: "What page ranges can I use for splitting?", a: "Enter ranges like '1-3', '5', or '7-10' to extract specific pages. You can extract single pages or multi-page ranges and download the result as a new PDF." },
  ],
  "pdf-editor": [
    { q: "What can I do with the PDF Editor?", a: "You can draw freehand, add typed text, highlight areas, erase content, add a watermark, fill form fields, and annotate PDFs — all directly in your browser without any upload." },
    { q: "Will editing change the original PDF file?", a: "No. The editor works on a copy in your browser. Your original file is unchanged. Download the edited version when satisfied." },
    { q: "Can I edit scanned PDFs?", a: "You can annotate and draw on scanned PDFs, but you cannot edit the underlying scanned text. For OCR-based text editing, dedicated software like Adobe Acrobat is needed." },
    { q: "Is there an undo function?", a: "Yes, use Ctrl+Z (or Cmd+Z on Mac) to undo the last action. Multiple undo steps are supported for drawing and text operations." },
    { q: "What watermark options are available?", a: "You can add a custom text watermark (e.g., 'CONFIDENTIAL', 'DRAFT') with adjustable opacity, size, and angle, applied across all pages of the PDF." },
  ],
  "zip-extractor": [
    { q: "Is extraction done in the browser?", a: "Yes, ZIP extraction uses JSZip and runs entirely in your browser. No files are uploaded to any server — your data stays private." },
    { q: "What archive formats are supported?", a: "Currently, ZIP files (.zip) are supported. RAR, 7z, and tar.gz formats are not supported as they require native binaries not available in browsers." },
    { q: "Can I extract password-protected ZIPs?", a: "Password-protected ZIPs are not supported in the current version. You would need a desktop application like 7-Zip or WinRAR to extract them." },
    { q: "How do I download specific files from a ZIP?", a: "After uploading, the tool lists all files in the archive. Click the download icon next to any file to download it individually without extracting the entire archive." },
    { q: "Is there a size limit for ZIP files?", a: "Since extraction is in-browser, the limit depends on your device's available RAM. ZIP files up to 500MB typically work fine on modern devices." },
  ],
  "csv-json-converter": [
    { q: "What is CSV format?", a: "CSV (Comma-Separated Values) is a plain text format where each line represents a data record and fields are separated by commas (or other delimiters). It is widely used for data exchange between spreadsheets and databases." },
    { q: "Can I use a custom delimiter instead of comma?", a: "Yes. The tool supports custom delimiters like semicolons (;), pipes (|), or tabs (\\t), which are common in European locale exports and TSV files." },
    { q: "How are nested objects handled when converting JSON to CSV?", a: "Nested JSON objects are flattened using dot notation (e.g., address.city becomes a column). Arrays within objects may be serialized as strings depending on the nesting depth." },
    { q: "Can I upload a CSV file directly?", a: "Yes, click the upload button to select a CSV file from your device. The tool parses it and converts it to formatted JSON instantly." },
    { q: "How do I handle CSV files with headers?", a: "The tool treats the first row as column headers by default and maps them as JSON keys. If your CSV has no headers, the columns will be labeled col_0, col_1, etc." },
  ],
  "xml-json-converter": [
    { q: "What is XML?", a: "XML (Extensible Markup Language) is a markup language for storing and transporting structured data using custom tags. It is human-readable and widely used in enterprise APIs, config files, and data exchange." },
    { q: "Can I convert a large XML file?", a: "Yes, you can paste or upload XML. For very large files (1MB+), processing may take a second but is handled entirely in your browser without any server upload." },
    { q: "How are XML attributes handled in JSON?", a: "XML attributes are typically converted to JSON keys prefixed with '@' (e.g., <item id='1'> becomes { '@id': '1' }). The exact behavior depends on the conversion library used." },
    { q: "Is the conversion lossless?", a: "Converting from XML to JSON and back may not be perfectly lossless because JSON has no direct equivalent of XML attributes, namespaces, or mixed content. Round-trip accuracy is best for simple data structures." },
    { q: "What is the difference between XML and JSON for APIs?", a: "JSON is lighter, easier to parse in JavaScript, and dominant in REST APIs. XML supports schemas (XSD), namespaces, and attributes, making it preferred in SOAP APIs and enterprise integrations." },
  ],
  "xml-csv-converter": [
    { q: "How does XML to CSV conversion work?", a: "The tool extracts repeating child elements from the XML (typically rows) and maps their sub-elements or attributes as CSV columns. It works best with flat or shallow XML structures." },
    { q: "What XML structures are supported?", a: "Simple flat XML (like <records><record><name>X</name></record></records>) converts cleanly. Deeply nested or mixed-content XML may not produce a clean CSV." },
    { q: "Can I upload an XML file?", a: "Yes. Click the upload button to select an XML file from your device. The tool parses it and presents the CSV output ready to copy or download." },
    { q: "How do I open the output CSV?", a: "Download the CSV file and open it in Microsoft Excel, Google Sheets, LibreOffice Calc, or any spreadsheet app. It will be auto-formatted into rows and columns." },
    { q: "Is this tool suitable for large XML files?", a: "It works well for files up to a few MB. For very large XML files (10MB+), a dedicated desktop tool or a server-side ETL pipeline is recommended." },
  ],
  "xml-formatter": [
    { q: "What does XML formatting do?", a: "XML formatting (pretty-printing) adds proper indentation and line breaks to minified or poorly indented XML, making it human-readable. Minification removes whitespace to reduce file size." },
    { q: "How do I validate XML?", a: "The formatter checks for well-formedness: matching open/close tags, proper nesting, single root element, and correct attribute quoting. Invalid XML is highlighted with an error message." },
    { q: "What is the difference between well-formed and valid XML?", a: "Well-formed XML follows syntax rules (proper tags, nesting). Valid XML also conforms to a schema (DTD or XSD) that defines allowed elements and attributes. Our tool checks well-formedness only." },
    { q: "Can I set custom indentation?", a: "Yes, you can choose 2 spaces, 4 spaces, or tab indentation for the formatted output." },
    { q: "Does the formatter support XML namespaces?", a: "Yes. Namespaced XML (xmlns:prefix attributes) is preserved correctly during formatting and minification." },
  ],
  "sql-formatter": [
    { q: "Which SQL dialects are supported?", a: "The formatter supports MySQL, PostgreSQL, SQLite, T-SQL (SQL Server), and standard ANSI SQL. Select your dialect to get dialect-appropriate keyword formatting." },
    { q: "Does formatting change the query logic?", a: "No. Formatting only affects whitespace, indentation, and keyword casing. It never changes the SQL logic, joins, or conditions." },
    { q: "Can I uppercase all SQL keywords automatically?", a: "Yes. Enable the 'Uppercase Keywords' option to convert SELECT, FROM, WHERE, JOIN, etc. to uppercase — the standard convention in most SQL style guides." },
    { q: "Can I paste queries with multiple statements?", a: "Yes, multiple SQL statements separated by semicolons are each formatted individually in sequence." },
    { q: "Does the formatter handle stored procedures?", a: "Basic stored procedure syntax (CREATE PROCEDURE, BEGIN/END blocks) is formatted. Complex PL/SQL or T-SQL procedural logic may have limited formatting support." },
  ],
  "java-formatter": [
    { q: "What does the Java formatter do?", a: "It auto-indents Java code, normalizes brace placement, adds consistent spacing around operators and keywords, and removes redundant blank lines — following standard Java style conventions." },
    { q: "Does it change my code logic?", a: "No. The formatter only affects whitespace and indentation. It never renames variables, removes code, or changes logic." },
    { q: "Can I upload a .java file?", a: "Yes. Click the upload button to select a .java file. The tool reads the file and displays the formatted output ready to copy." },
    { q: "Does it support Java 17+ features?", a: "Yes, the formatter handles modern Java syntax including records, sealed classes, text blocks, pattern matching, and switch expressions introduced in Java 14–21." },
    { q: "Is there a character limit?", a: "The tool handles typical Java class files comfortably. For extremely large generated files (10,000+ lines), consider using an IDE formatter (IntelliJ IDEA, Eclipse) instead." },
  ],
};

import type { ToolDescriptionData } from "@/components/shared/ToolDescription";

export const toolDescriptions: Record<string, ToolDescriptionData> = {
  "sip-calculator": {
    whatIs: "A SIP Calculator estimates the future value of your mutual fund investments made at regular monthly intervals. It uses compound interest math to show how small, disciplined contributions grow into a large corpus over time — demonstrating the power of rupee cost averaging.",
    howToUse: [
      "Enter your monthly SIP amount (e.g. ₹5,000)",
      "Set the expected annual return rate (typical equity funds: 10–14%)",
      "Choose your investment duration in years",
      "Optionally set an Annual Step-Up % to increase your SIP each year",
      "Toggle 'Inflation Adjusted' to see returns in today's purchasing power",
    ],
    example: "Investing ₹5,000/month for 10 years at 12% annual return: you invest ₹6 lakh total and accumulate approximately ₹11.6 lakh. Add a 10% annual step-up and the corpus grows to over ₹18 lakh from the same starting amount.",
    whyUse: [
      "Plan for long-term goals like retirement, children's education, or buying a home",
      "Compare SIP vs lumpsum strategies side by side",
      "Understand the compounding effect and why starting early matters",
      "Model inflation-adjusted real returns to see actual purchasing power",
    ],
  },
  "emi-calculator": {
    whatIs: "An EMI Calculator computes your Equated Monthly Installment — the fixed monthly amount you pay to repay a loan. It breaks each payment into principal and interest components and generates a full amortization schedule so you can see exactly where your money goes each month.",
    howToUse: [
      "Enter the loan principal amount (e.g. ₹20,00,000 for a home loan)",
      "Input the annual interest rate offered by your bank",
      "Set the loan tenure in years",
      "View your monthly EMI, total interest payable, and total repayment amount",
      "Scroll down to see the month-by-month amortization table",
    ],
    example: "A ₹20 lakh home loan at 8.5% for 20 years gives an EMI of ₹17,356/month. Total repayment: ₹41.65 lakh — meaning ₹21.65 lakh goes purely to interest. Reducing tenure to 15 years raises EMI to ₹19,680 but saves over ₹7 lakh in interest.",
    whyUse: [
      "Compare different loan amounts, tenures, and rates before applying",
      "Budget your monthly expenses accurately around the EMI",
      "See exactly how much interest a longer tenure costs you",
      "Negotiate smarter with your bank using accurate numbers",
    ],
  },
  "gst-calculator": {
    whatIs: "A GST Calculator quickly computes Goods and Services Tax for any transaction. You can add GST to a base price or reverse-calculate to extract the base price from a GST-inclusive amount — with automatic CGST and SGST split for intra-state transactions.",
    howToUse: [
      "Choose 'Add GST' to add tax to a base price, or 'Remove GST' to extract the base from an inclusive price",
      "Enter the amount",
      "Select the applicable GST slab (5%, 12%, 18%, or 28%) or enter a custom rate",
      "Instantly view the base amount, GST amount (split into CGST + SGST), and total",
    ],
    example: "A freelancer bills ₹50,000 for a service at 18% GST. Adding GST: ₹50,000 × 1.18 = ₹59,000 total invoice. The client pays ₹59,000; CGST = ₹4,500 and SGST = ₹4,500 are deposited with the government.",
    whyUse: [
      "Quickly calculate invoice totals inclusive of GST",
      "Reverse-calculate the pre-tax base price from a GST-inclusive quote",
      "Understand the CGST/SGST split for intra-state billing",
      "Verify GST amounts on invoices you receive",
    ],
  },
  "percentage-calculator": {
    whatIs: "A Percentage Calculator solves all common percentage problems instantly — finding what percent one number is of another, calculating percentage increase or decrease, finding the original value after a discount, and more. It handles the mental math that slows you down.",
    howToUse: [
      "Select the type of calculation: 'X% of Y', 'X is what % of Y', 'percentage change', or 'reverse percentage'",
      "Enter the required values in the input fields",
      "The result appears instantly without pressing any button",
      "Use the copy button to copy the result",
    ],
    example: "You want to know the effective price after a 30% discount on ₹1,200: 30% of ₹1,200 = ₹360 discount → final price ₹840. Or reverse: if ₹840 is the price after a 30% discount, original price = ₹840 ÷ 0.70 = ₹1,200.",
    whyUse: [
      "Calculate discounts, markups, and profit margins instantly",
      "Find percentage change between two values (e.g. salary hike, price inflation)",
      "Work out GST, TDS, or commission percentages quickly",
      "Useful for students, shoppers, accountants, and business owners alike",
    ],
  },
  "age-calculator": {
    whatIs: "An Age Calculator finds your exact age in years, months, and days from your date of birth to any target date (default: today). It also tells you the day of the week you were born, days until your next birthday, and useful age milestones relevant in India.",
    howToUse: [
      "Enter your date of birth using the date picker",
      "Optionally change the 'As on date' to calculate age at any past or future date",
      "View your exact age in years, months, days, hours, and total days lived",
      "See the day of the week you were born and days until your next birthday",
    ],
    example: "Born on 15 August 1995 → As of 1 July 2026 → Age: 30 years, 10 months, 16 days. Total days lived: 11,278. Next birthday: 45 days away. Born on a Tuesday.",
    whyUse: [
      "Verify age for government documents, loan applications, and insurance policies",
      "Check eligibility for age-based benefits (senior citizen tax, pension, voting)",
      "Calculate exact age for school or competitive exam admission cut-offs",
      "Quickly find age difference between two people",
    ],
  },
  "fd-calculator": {
    whatIs: "A Fixed Deposit Calculator computes the maturity amount and interest earned on your FD based on the principal, interest rate, tenure, and compounding frequency. It includes preset rates for major Indian banks like SBI, HDFC, and ICICI so you can compare returns instantly.",
    howToUse: [
      "Enter your deposit amount (principal)",
      "Select a bank preset to auto-fill the current rate, or enter a custom rate",
      "Set the FD tenure in years and months",
      "Choose the compounding frequency (monthly, quarterly, annually)",
      "View maturity amount, total interest earned, and effective annual yield",
    ],
    example: "₹1,00,000 deposited in SBI FD at 6.8% for 3 years with quarterly compounding matures to approximately ₹1,22,164. Interest earned: ₹22,164 — taxable as income at your slab rate.",
    whyUse: [
      "Compare FD returns across banks before locking in your money",
      "Understand the impact of compounding frequency on returns",
      "Plan for TDS implications if interest exceeds ₹40,000/year",
      "Evaluate FDs vs debt mutual funds for post-tax returns",
    ],
  },
  "ppf-calculator": {
    whatIs: "A PPF Calculator projects your Public Provident Fund corpus year by year, accounting for the 7.1% sovereign-guaranteed interest rate and the 15-year lock-in. PPF is one of India's most popular tax-saving instruments with EEE (Exempt-Exempt-Exempt) status.",
    howToUse: [
      "Enter your annual PPF contribution (₹500 to ₹1,50,000)",
      "Set the investment period (minimum 15 years, extendable in 5-year blocks)",
      "The calculator applies the current 7.1% interest rate compounded annually",
      "View year-by-year balance, interest credited, and final maturity corpus",
    ],
    example: "Investing ₹1,50,000/year (maximum) for 15 years at 7.1%: total contribution ₹22.5 lakh → maturity corpus ≈ ₹40.7 lakh. All interest and maturity proceeds are completely tax-free.",
    whyUse: [
      "Plan your Section 80C investments and maximize the ₹1.5 lakh deduction",
      "Model long-term wealth accumulation with zero credit risk",
      "Compare PPF vs ELSS mutual funds for tax-saving investments",
      "Decide whether to extend PPF beyond 15 years with or without contributions",
    ],
  },
  "income-tax-calculator": {
    whatIs: "An Income Tax Calculator computes your tax liability for FY 2025-26 under both the old and new tax regimes, accounting for deductions like 80C, 80D, HRA, and standard deduction. It helps you choose the more beneficial regime before filing your ITR.",
    howToUse: [
      "Enter your annual gross salary or total income",
      "Add applicable deductions: 80C (up to ₹1.5L), 80D (health insurance), HRA, LTA, etc.",
      "The calculator shows tax under both old and new regimes side by side",
      "Compare the two regimes and pick the one with lower tax liability",
    ],
    example: "Annual salary ₹12,00,000. Old regime: with ₹1.5L 80C + ₹25K 80D + ₹50K standard deduction → taxable income ₹9,75,000 → tax ≈ ₹1,17,000. New regime: ₹75K standard deduction only → taxable ₹11,25,000 → tax ≈ ₹97,500. New regime saves ₹19,500 here.",
    whyUse: [
      "Decide which tax regime saves you more money before the financial year begins",
      "Estimate your advance tax installments to avoid interest penalties",
      "Plan salary restructuring to maximize HRA and allowance exemptions",
      "Understand how deductions reduce your effective tax rate",
    ],
  },
  "ctc-calculator": {
    whatIs: "A CTC (Cost to Company) Calculator breaks down your total compensation package into monthly in-hand salary after all deductions. It shows exactly how much of your CTC actually reaches your bank account versus going to PF, gratuity, TDS, and other components.",
    howToUse: [
      "Enter your annual CTC amount",
      "Specify your city type (metro/non-metro) for correct HRA calculation",
      "Add any existing exemptions or special allowances if known",
      "View the full salary breakup: basic, HRA, allowances, PF deductions, and net take-home",
    ],
    example: "CTC of ₹12 LPA: Basic ₹4.8L + HRA ₹2.4L + allowances ₹2.4L + employer PF ₹57.6K + gratuity ₹23K. After deducting employee PF ₹57.6K and TDS ≈ ₹28K, monthly in-hand ≈ ₹73,700.",
    whyUse: [
      "Understand your actual take-home before accepting a job offer",
      "Compare offers from different companies using a consistent breakdown",
      "Negotiate salary components (higher HRA = lower taxable income)",
      "Plan your monthly budget based on accurate in-hand salary",
    ],
  },
  "compound-interest-calculator": {
    whatIs: "A Compound Interest Calculator computes investment growth where interest is earned on both the original principal and all previously accumulated interest. Unlike simple interest, compounding causes exponential growth — and its effect becomes dramatically visible over long time horizons.",
    howToUse: [
      "Enter the principal amount (initial investment)",
      "Set the annual interest rate",
      "Choose the compounding frequency: daily, monthly, quarterly, half-yearly, or annually",
      "Enter the investment duration in years",
      "View total maturity amount, interest earned, and a year-by-year growth chart",
    ],
    example: "₹1,00,000 invested at 10% for 20 years: with annual compounding → ₹6,72,750 (interest: ₹5,72,750). With monthly compounding → ₹7,32,817 — that's ₹60,000 more from compounding frequency alone.",
    whyUse: [
      "Visualize the exponential growth of long-term investments",
      "Compare compounding frequencies to maximize returns on FDs and bonds",
      "Understand why time in the market matters more than timing the market",
      "Apply the Rule of 72 to estimate when any investment will double",
    ],
  },
  "cagr-calculator": {
    whatIs: "A CAGR (Compound Annual Growth Rate) Calculator finds the steady annual growth rate that takes an investment from a starting value to an ending value over a given period. It is the standard metric for comparing investment performance across different asset classes and time frames.",
    howToUse: [
      "Enter the initial investment value",
      "Enter the final value after growth",
      "Enter the number of years",
      "View the CAGR percentage — the equivalent annual return over the period",
      "Or use reverse mode: enter a target CAGR to find the required future value",
    ],
    example: "Portfolio value grew from ₹5,00,000 in 2019 to ₹9,50,000 in 2024 (5 years). CAGR = (9,50,000 / 5,00,000)^(1/5) − 1 = 13.7% per year. This is better than FD (7%) but below a top large-cap fund (15%).",
    whyUse: [
      "Compare investment performance across different assets on a fair annual basis",
      "Evaluate mutual fund or stock portfolio returns vs benchmarks",
      "Set realistic return expectations for financial planning",
      "Calculate the growth rate of business revenue or any metric over time",
    ],
  },
  "loan-eligibility-calculator": {
    whatIs: "A Loan Eligibility Calculator estimates the maximum loan amount a bank will sanction based on your monthly income, existing EMIs, interest rate, and tenure. Banks use FOIR (Fixed Obligation to Income Ratio) — typically 40–50% — to determine how much EMI you can afford.",
    howToUse: [
      "Enter your net monthly income (post-tax take-home)",
      "Add the total of any existing EMIs you are paying",
      "Set the loan interest rate and desired tenure",
      "Adjust the FOIR % if you know your bank's specific policy",
      "View your maximum eligible loan amount and the maximum permissible EMI",
    ],
    example: "Net monthly income: ₹80,000. Existing EMIs: ₹10,000. Bank FOIR: 50% → permissible total EMI: ₹40,000 → new EMI headroom: ₹30,000. At 8.5% for 20 years → maximum home loan eligibility: ≈ ₹31.5 lakh.",
    whyUse: [
      "Know your loan eligibility before approaching a bank, avoiding rejection",
      "Plan whether to pay off existing loans before applying for a new one",
      "Compare eligibility at different tenures and interest rates",
      "Decide how much down payment to arrange to cover the gap between property price and eligible loan",
    ],
  },
  "json-formatter": {
    whatIs: "A JSON Formatter beautifies minified or compressed JSON into a human-readable indented format. It also validates JSON syntax, minifies pretty-printed JSON for network transmission, and helps you spot errors like missing commas, mismatched brackets, or incorrect data types.",
    howToUse: [
      "Paste your JSON string into the input area, or upload a .json file",
      "Click 'Format' to prettify with proper indentation, or 'Minify' to compress",
      "Validation errors are highlighted with the line number and description",
      "Use the copy button to copy the formatted output to your clipboard",
    ],
    example: "{\"name\":\"Ravi\",\"age\":30,\"city\":\"Mumbai\"} formatted becomes:\n{\n  \"name\": \"Ravi\",\n  \"age\": 30,\n  \"city\": \"Mumbai\"\n}",
    whyUse: [
      "Debug API responses and config files by making them readable",
      "Validate JSON before sending it to an API or saving to a database",
      "Minify JSON to reduce payload size for web applications",
      "Quickly inspect deeply nested JSON structures with tree-like indentation",
    ],
  },
  "qr-code-generator": {
    whatIs: "A QR Code Generator creates scannable QR codes for URLs, UPI payment IDs, phone numbers, SMS, email addresses, and plain text. QR codes can be scanned by any smartphone camera to instantly open a link, initiate a payment, or save contact information.",
    howToUse: [
      "Select the content type: URL, UPI, Phone, SMS, Email, or Text",
      "Enter the corresponding value (e.g. a URL or UPI ID like yourname@upi)",
      "Choose the error correction level (L for digital, H for printed materials)",
      "Download the QR code as PNG for immediate use",
    ],
    example: "For a business accepting UPI payments: select UPI type, enter your UPI ID (e.g. shop@okaxis), download the QR code, print and display at your counter. Customers scan with PhonePe, Google Pay, or Paytm to pay instantly.",
    whyUse: [
      "Accept UPI payments without a physical POS terminal",
      "Share website links via printed flyers, business cards, and packaging",
      "Enable quick dialing or contact saving from brochures",
      "Create contactless menus, feedback forms, or event check-ins",
    ],
  },
  "word-counter": {
    whatIs: "A Word Counter counts words, characters, sentences, and paragraphs in any text. It also estimates reading time, speaking time, and shows keyword frequency analysis — useful for writers, bloggers, students, and social media managers tracking content length.",
    howToUse: [
      "Paste or type your text into the editor",
      "Word count, character count, and sentence count update in real time",
      "View estimated reading time (based on 200 WPM average)",
      "Scroll down to see the top 10 most frequent keywords in your text",
    ],
    example: "A 500-word blog introduction has ~2,800 characters, approximately 25 sentences, and a reading time of about 2.5 minutes. The keyword frequency section reveals which terms you've overused and should vary.",
    whyUse: [
      "Stay within word limits for essays, assignments, job applications, and social posts",
      "Optimize blog posts for SEO target length (typically 1,500–2,500 words)",
      "Check keyword density to avoid over-optimization in content",
      "Estimate reading and speaking time for presentations or podcasts",
    ],
  },
  "base64-tool": {
    whatIs: "A Base64 Tool encodes any text or file into Base64 format, or decodes Base64 strings back to their original content. Base64 is a binary-to-text encoding scheme that makes binary data safe for transmission in text-based protocols like HTTP headers, JSON, and email.",
    howToUse: [
      "Switch between 'Encode' and 'Decode' mode using the toggle",
      "Paste your text or Base64 string into the input field",
      "Or upload any file to encode it to Base64",
      "The output appears instantly — use the copy button to copy the result",
    ],
    example: "Encoding the text 'Hello, India!' → 'SGVsbG8sIEluZGlhIQ=='. Decoding 'SGVsbG8sIEluZGlhIQ==' → 'Hello, India!'. The = padding at the end is normal for Base64.",
    whyUse: [
      "Embed images directly in HTML or CSS as data URIs to reduce HTTP requests",
      "Encode JWT tokens and API credentials for safe URL transmission",
      "Transfer binary files through text-only channels like JSON APIs",
      "Debug base64-encoded data in HTTP requests or config files",
    ],
  },
  "text-case-converter": {
    whatIs: "A Text Case Converter transforms any text between common formatting styles — UPPER CASE, lower case, Title Case, camelCase, PascalCase, snake_case, kebab-case, and more. It is essential for developers formatting variable names and writers standardizing headings.",
    howToUse: [
      "Type or paste your text into the input field",
      "Click any conversion button: UPPER, lower, Title, camelCase, PascalCase, snake_case, kebab-case, or Sentence case",
      "The converted text appears instantly in the output area",
      "Copy the result with the copy button",
    ],
    example: "Input: 'user first name' → camelCase: 'userFirstName' → PascalCase: 'UserFirstName' → snake_case: 'user_first_name' → kebab-case: 'user-first-name' → UPPER CASE: 'USER FIRST NAME'",
    whyUse: [
      "Quickly format variable and function names to match your codebase's naming convention",
      "Standardize blog post titles and headings to Title Case",
      "Convert database column names between snake_case and camelCase",
      "Fix accidental all-caps text from typing with Caps Lock on",
    ],
  },
  "unit-converter": {
    whatIs: "A Unit Converter converts measurements across weight, length, area, volume, temperature, speed, and data size — including traditional Indian units like Tola, Maund, Bigha, and Katha that are absent from most international tools.",
    howToUse: [
      "Select the measurement category (weight, length, area, volume, temperature, etc.)",
      "Enter the value you want to convert",
      "Select the source unit and the target unit",
      "The converted value appears instantly",
    ],
    example: "A land deal is quoted as 2 Bigha in UP. Converting: 2 Bigha = 54,000 sq ft (27,000 sq ft per Bigha in UP) = 5,017 sq metres = 0.5 hectares. Or: 100°F body temperature = (100−32) × 5/9 = 37.78°C.",
    whyUse: [
      "Convert traditional Indian land measurements (Bigha, Katha, Gunta) for real estate deals",
      "Convert gold weight between Tola, grams, and ounces for jewelry purchases",
      "Handle international unit conversions for work or education",
      "Convert cooking and recipe measurements between metric and imperial systems",
    ],
  },
  "invoice-generator": {
    whatIs: "An Invoice Generator creates professional, GST-compliant invoices with automatic CGST/SGST or IGST calculation based on whether the transaction is intra-state or inter-state. Download your invoice as a PDF instantly — no account or software required.",
    howToUse: [
      "Enter your business name, address, and GSTIN",
      "Add client details and a unique invoice number",
      "Add line items with quantity, rate, and applicable GST rate",
      "Select transaction type (intra-state for CGST+SGST, inter-state for IGST)",
      "Preview and download the invoice as PDF",
    ],
    example: "A Delhi-based consultant bills a Mumbai client ₹50,000 for services at 18% GST. Since it is inter-state, IGST of ₹9,000 applies. Total invoice value: ₹59,000. For a Delhi-to-Delhi invoice, the same ₹9,000 GST splits into CGST ₹4,500 + SGST ₹4,500.",
    whyUse: [
      "Create legally valid GST invoices without purchasing billing software",
      "Ensure correct CGST/SGST vs IGST split to avoid GST filing errors",
      "Maintain professional branding with customizable templates",
      "Generate invoices instantly for freelancers, consultants, and small businesses",
    ],
  },
  "salary-slip-generator": {
    whatIs: "A Salary Slip Generator creates professional monthly salary slips with a detailed breakup of earnings (basic, HRA, allowances) and deductions (PF, TDS, professional tax). Download as PDF to share with employees or use as income proof for loans and visa applications.",
    howToUse: [
      "Enter employee details: name, designation, employee ID, and department",
      "Add your company name, address, and optional logo",
      "Fill in salary components: basic, HRA, conveyance, special allowances",
      "Add deductions: employee PF, TDS, professional tax, and any other deductions",
      "Choose a template style and download as PDF",
    ],
    example: "Employee with CTC ₹6 LPA: Basic ₹20,000 + HRA ₹10,000 + allowances ₹10,000 = Gross ₹40,000. Deductions: PF ₹2,400 + Prof. Tax ₹200 = ₹2,600. Net take-home: ₹37,400/month.",
    whyUse: [
      "Issue compliant salary slips to employees without HR software",
      "Create salary proof for freelancers or self-employed individuals for loan or visa applications",
      "Maintain professional payroll records for audits and compliance",
      "Provide employees with clear visibility into their earnings and deductions",
    ],
  },
  "color-converter": {
    whatIs: "A Color Converter translates color values between HEX (#FF6200), RGB (255, 98, 0), and HSL (23°, 100%, 50%) formats with a live preview. It is essential for web designers and developers who work across different design tools that use different color formats.",
    howToUse: [
      "Pick a color using the color picker, or type a HEX, RGB, or HSL value directly",
      "The other two formats update automatically with the equivalent values",
      "Use the copy buttons to copy any format to your clipboard",
      "The live preview shows exactly what the color looks like",
    ],
    example: "Brand color #1DA462 (a green): RGB(29, 164, 98) — use in CSS as rgb(29, 164, 98). HSL(151°, 70%, 38%) — use in CSS as hsl(151, 70%, 38%). Adjust lightness in HSL to create shades and tints without touching hue.",
    whyUse: [
      "Convert design tool colors (Figma uses HEX, some tools use RGB) for CSS code",
      "Create accessible color variations by adjusting HSL lightness",
      "Match brand colors precisely across different platforms and file formats",
      "Quickly find the HEX code for any color you can visually pick",
    ],
  },
  "csv-json-converter": {
    whatIs: "A CSV ↔ JSON Converter transforms tabular CSV data into structured JSON and vice versa. It is used by developers, data analysts, and business users to move data between spreadsheets, APIs, and databases that use different formats.",
    howToUse: [
      "Select 'CSV to JSON' or 'JSON to CSV' mode",
      "Paste your data or upload a file (.csv or .json)",
      "Set the delimiter if your CSV uses a character other than comma (e.g. semicolon or tab)",
      "View the converted output and download or copy it",
    ],
    example: "CSV: name,age,city\\nRavi,30,Mumbai\\nPriya,25,Delhi → JSON: [{\"name\":\"Ravi\",\"age\":\"30\",\"city\":\"Mumbai\"},{\"name\":\"Priya\",\"age\":\"25\",\"city\":\"Delhi\"}]",
    whyUse: [
      "Convert Excel/Sheets exports (CSV) to JSON for use in web apps or APIs",
      "Transform API JSON responses to CSV for analysis in spreadsheet tools",
      "Migrate data between systems that accept different formats",
      "Quickly inspect the structure of CSV data in a readable JSON format",
    ],
  },
  "xml-json-converter": {
    whatIs: "An XML ↔ JSON Converter transforms data between XML (used in enterprise APIs, config files, and SOAP services) and JSON (used in REST APIs and modern web apps). It preserves the data structure while converting the syntax between the two formats.",
    howToUse: [
      "Select 'XML to JSON' or 'JSON to XML' conversion direction",
      "Paste your XML or JSON, or upload a file",
      "The converted output appears in the right panel",
      "Copy or download the result",
    ],
    example: "<person><name>Ravi</name><age>30</age></person> converts to {\"person\":{\"name\":\"Ravi\",\"age\":\"30\"}}. Useful when integrating a SOAP-based legacy system with a modern JSON REST API.",
    whyUse: [
      "Integrate legacy SOAP/XML APIs with modern REST/JSON systems",
      "Convert XML config files to JSON for web application configuration",
      "Inspect and debug XML payloads in a more readable JSON format",
      "Transform data formats during ETL and data migration pipelines",
    ],
  },
  "xml-csv-converter": {
    whatIs: "An XML ↔ CSV Converter extracts tabular data from XML files and converts it to CSV for spreadsheet analysis, or wraps CSV rows into an XML structure for systems that require XML input. It bridges the gap between document-oriented and tabular data formats.",
    howToUse: [
      "Select 'XML to CSV' or 'CSV to XML' mode",
      "Paste or upload your data",
      "For XML to CSV, the tool detects repeating elements and maps them to rows",
      "Download the result as a .csv or .xml file",
    ],
    example: "<employees><employee><name>Ravi</name><dept>Engineering</dept></employee></employees> → CSV: name,dept\\nRavi,Engineering. Open in Excel to analyze or filter employee records.",
    whyUse: [
      "Export XML report data into Excel-friendly CSV format",
      "Prepare CSV data in XML format for ERP or enterprise systems",
      "Simplify analysis of XML data exports from databases and APIs",
      "Batch convert data files without writing custom parsing scripts",
    ],
  },
  "xml-formatter": {
    whatIs: "An XML Formatter (pretty-printer) adds proper indentation and line breaks to raw or minified XML, making it human-readable. It also validates well-formedness — checking for matching tags, correct nesting, and proper attribute syntax — and can minify XML to reduce payload size.",
    howToUse: [
      "Paste your XML or upload an .xml file",
      "Click 'Format' to prettify with indentation, or 'Minify' to compress",
      "Select indentation style: 2 spaces, 4 spaces, or tabs",
      "Any syntax errors are highlighted with a description",
    ],
    example: "<root><item id='1'><name>Widget</name><price>99</price></item></root> formatted with 2-space indent becomes a clearly readable 6-line XML block. Minified back to one line for API transmission.",
    whyUse: [
      "Debug API XML responses that arrive as unreadable single-line strings",
      "Validate XML files before importing into databases or applications",
      "Minify XML config files to reduce bundle size in applications",
      "Review XML structure when building or testing SOAP API integrations",
    ],
  },
  "sql-formatter": {
    whatIs: "A SQL Formatter beautifies SQL queries by adding proper indentation, line breaks, and keyword casing — transforming a single unreadable line of SQL into a structured, maintainable query. It supports MySQL, PostgreSQL, SQLite, and SQL Server dialects.",
    howToUse: [
      "Paste your SQL query into the input area",
      "Select your SQL dialect (MySQL, PostgreSQL, SQLite, T-SQL, etc.)",
      "Toggle 'Uppercase Keywords' to apply the standard convention",
      "Click 'Format' and copy the formatted query",
    ],
    example: "select u.name,o.total from users u inner join orders o on u.id=o.user_id where o.total>1000 order by o.total desc → formatted into a clean 6-line query with uppercase keywords and proper JOIN indentation.",
    whyUse: [
      "Improve SQL readability before sharing queries in code reviews or documentation",
      "Standardize query formatting across a team's codebase",
      "Debug complex queries by making JOIN and WHERE conditions visually clear",
      "Format auto-generated or ORM-produced SQL for manual inspection",
    ],
  },
  "java-formatter": {
    whatIs: "A Java Formatter auto-indents and cleans Java source code, normalizing brace placement, spacing around operators, and blank line usage according to standard Java style conventions (similar to Google Java Style Guide). It works on any Java code from Java 8 through Java 21.",
    howToUse: [
      "Paste Java code or upload a .java file",
      "Click 'Format' to apply standard Java formatting",
      "Copy the formatted code or download it as a .java file",
      "For large codebases, use your IDE's built-in formatter (IntelliJ/Eclipse) instead",
    ],
    example: "Pasting unindented Java code with inconsistent spacing → formatter applies consistent 4-space indentation, places opening braces on the same line as the method signature, and normalizes spaces around operators.",
    whyUse: [
      "Clean up code before submitting to code review or open-source projects",
      "Standardize formatting when merging code from multiple contributors",
      "Quickly reformat code pasted from documentation or Stack Overflow",
      "Prepare Java code samples for blog posts or technical documentation",
    ],
  },
  "image-converter": {
    whatIs: "An Image Converter transforms images between PNG, JPG, and WebP formats entirely in your browser. PNG is lossless with transparency support; JPG is best for photographs; WebP is the modern format offering superior compression for web performance.",
    howToUse: [
      "Upload your image by clicking the upload area or dragging and dropping",
      "Select the target format: PNG, JPG, or WebP",
      "Adjust the quality slider (for JPG and WebP) to balance file size vs quality",
      "Click 'Convert' and download the result",
    ],
    example: "A 2MB PNG product image converted to WebP at 85% quality → approximately 400KB — a 80% size reduction with no visible quality loss. Use WebP on your website to improve page load speed and Core Web Vitals scores.",
    whyUse: [
      "Convert PNG to WebP for faster website loading and better SEO scores",
      "Convert JPG to PNG to preserve quality when editing images repeatedly",
      "Reduce image file size before uploading to websites, apps, or WhatsApp",
      "All conversion is done locally — your images are never uploaded to a server",
    ],
  },
  "image-compressor": {
    whatIs: "An Image Compressor reduces the file size of images (PNG, JPG, WebP) by re-encoding them at a lower quality setting or resizing their dimensions. All processing happens in your browser — images are never uploaded to any server.",
    howToUse: [
      "Upload one or more images by clicking or dragging and dropping",
      "Adjust the quality slider (lower % = smaller file, more compression)",
      "Optionally set maximum width or height to resize the image proportionally",
      "Click 'Compress' and download the compressed image",
    ],
    example: "A 3MB JPG photo at 100% quality compressed to 75% quality → approximately 600KB (80% reduction) with minimal visible quality loss. Adding a max-width of 1920px further reduces it if the source was larger.",
    whyUse: [
      "Optimize images for websites to improve page speed and reduce bandwidth costs",
      "Reduce WhatsApp/email attachment size before sharing",
      "Batch compress product photos before uploading to e-commerce platforms",
      "All processing is private and local — no cloud upload required",
    ],
  },
  "pdf-tools": {
    whatIs: "PDF Tools lets you merge multiple PDFs into one, split a PDF into individual pages or page ranges, and compress a PDF to reduce its file size — all directly in your browser without uploading to any server, keeping your documents completely private.",
    howToUse: [
      "Select the operation: Merge, Split, or Compress",
      "For Merge: upload multiple PDF files and arrange their order",
      "For Split: upload one PDF and specify the page ranges to extract",
      "For Compress: upload a PDF and click compress to reduce its size",
      "Download the resulting PDF",
    ],
    example: "You have 5 separate invoice PDFs for a month. Use Merge to combine them into one document before emailing to your accountant. Or use Split to extract pages 3–5 from a 20-page report and share only the relevant section.",
    whyUse: [
      "Combine multiple documents into a single PDF for submission or sharing",
      "Extract specific pages from large PDFs without Adobe Acrobat",
      "Reduce email attachment size by compressing large PDFs",
      "All processing is local — sensitive documents never leave your device",
    ],
  },
  "pdf-editor": {
    whatIs: "A PDF Editor lets you annotate, draw, add text, erase content, add watermarks, and fill form fields in any PDF — entirely in your browser. No software installation required, and your documents are never uploaded to any external server.",
    howToUse: [
      "Upload a PDF file by clicking the upload area",
      "Select a tool: Draw (freehand), Text (add typed text), Erase, or Watermark",
      "Make your annotations on the PDF canvas",
      "Navigate between pages using the page controls",
      "Download the annotated PDF when finished",
    ],
    example: "Received a contract PDF that needs your signature and date: use the Draw tool to sign, the Text tool to type the date, and download the signed PDF — no printing, scanning, or Adobe needed.",
    whyUse: [
      "Sign documents and fill forms without printing and scanning",
      "Add 'DRAFT', 'CONFIDENTIAL', or 'APPROVED' watermarks to PDFs",
      "Annotate PDFs for review without software installation",
      "All edits are private and done locally in your browser",
    ],
  },
  "zip-extractor": {
    whatIs: "A ZIP Extractor unpacks ZIP archive files directly in your browser, showing you all contained files and letting you download them individually or all at once. No software installation needed, and your files are never uploaded to any server.",
    howToUse: [
      "Click the upload area or drag and drop a .zip file",
      "The tool lists all files and folders inside the archive",
      "Click the download icon next to any file to download it individually",
      "Or click 'Download All' to extract the entire archive",
    ],
    example: "You received a ZIP with 10 invoice PDFs from a vendor. Upload the ZIP, preview all file names, and download only the 3 invoices you need — without extracting everything to your desktop.",
    whyUse: [
      "Extract specific files from a ZIP without installing WinRAR or 7-Zip",
      "Preview ZIP contents before deciding what to extract",
      "Access ZIP files on mobile or Chromebook where extraction software isn't available",
      "Files are processed locally — no cloud upload, complete privacy",
    ],
  },
  "number-base-converter": {
    whatIs: "A Number Base Converter translates numbers between binary (base-2), octal (base-8), decimal (base-10), and hexadecimal (base-16) with bit-level visualization. It is a must-have tool for computer science students, developers, and anyone working with low-level programming or digital systems.",
    howToUse: [
      "Type a number in any base field: binary, octal, decimal, or hexadecimal",
      "All other base representations update instantly",
      "View the binary representation with bit grouping for easy reading",
      "Use the bit-length selector (8-bit, 16-bit, 32-bit) to see representations with leading zeros",
    ],
    example: "Decimal 255 = Binary 11111111 = Octal 377 = Hexadecimal FF. This is why web colors max out at #FFFFFF — 255 (maximum RGB value) is FF in hex. chmod 755 in Unix = binary 111 101 101 (owner: rwx, group: r-x, others: r-x).",
    whyUse: [
      "Convert between number systems for programming and computer science coursework",
      "Understand binary representations for bitwise operations and flags",
      "Decode hex color codes, memory addresses, and file offsets",
      "Verify octal permissions in Unix/Linux systems (chmod)",
    ],
  },
  "timestamp-converter": {
    whatIs: "A Timestamp Converter transforms Unix epoch timestamps (seconds since 1 January 1970 UTC) into human-readable dates and times in IST, UTC, and ISO 8601 format — and converts any date back to a Unix timestamp. It also shows a live real-time epoch counter.",
    howToUse: [
      "Paste a Unix timestamp (e.g. 1751366400) to convert it to a readable date",
      "Or enter a date and time to get the corresponding Unix timestamp",
      "Toggle between seconds and milliseconds (JavaScript uses milliseconds)",
      "View the result in IST (UTC+5:30), UTC, and ISO 8601 format simultaneously",
    ],
    example: "Unix timestamp 1751366400 → 1 July 2026, 05:30:00 IST (00:00:00 UTC). Converting back: 1 July 2026 00:00:00 UTC → 1751328000. JavaScript Date.now() returns milliseconds: 1751366400000.",
    whyUse: [
      "Debug API responses that return Unix timestamps instead of readable dates",
      "Convert database timestamp fields for log analysis and monitoring",
      "Understand token expiry times in JWT 'exp' claims",
      "Handle timezone conversions between UTC and IST (UTC+5:30)",
    ],
  },
  "regex-tester": {
    whatIs: "A Regex Tester lets you write and test regular expressions against sample text with live match highlighting. It supports all standard JavaScript regex flags (global, case-insensitive, multiline, dotAll) and includes common Indian patterns like PAN, Aadhaar, mobile numbers, and GST numbers.",
    howToUse: [
      "Enter your regular expression in the pattern field (without slashes)",
      "Select flags: g (global), i (ignore case), m (multiline), s (dotAll)",
      "Type or paste your test text below",
      "All matches are highlighted in real time with count and captured groups shown",
    ],
    example: "Pattern: ^[6-9]\\d{9}$ with the test string '9876543210' → matches (valid Indian mobile number). Pattern: [A-Z]{5}[0-9]{4}[A-Z] with 'ABCDE1234F' → matches (valid PAN format).",
    whyUse: [
      "Test and debug regex patterns without running code",
      "Validate Indian-specific formats: PAN, GST number, Aadhaar, PIN codes, mobile numbers",
      "Learn regex visually by seeing which parts of text match in real time",
      "Build input validation patterns for web forms and APIs",
    ],
  },
  "jwt-decoder": {
    whatIs: "A JWT Decoder splits a JSON Web Token into its three parts — header, payload, and signature — and displays the decoded content. It shows the algorithm used, all claims including expiration time, and whether the token is currently valid or expired.",
    howToUse: [
      "Paste a JWT token (the three-part string separated by dots) into the input field",
      "The header and payload are decoded and displayed as formatted JSON instantly",
      "Check the 'exp' claim to see the expiration time in human-readable format",
      "Note: this tool only decodes — it does not verify the signature",
    ],
    example: "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMjMiLCJleHAiOjE3NTEzNjY0MDB9.xxx decoded: Header: {alg: 'HS256', typ: 'JWT'}. Payload: {userId: '123', exp: 1751366400 → 1 Jul 2026 05:30 IST}.",
    whyUse: [
      "Inspect JWT tokens during API development and debugging",
      "Check token expiry without writing code to decode it manually",
      "Verify the payload contents (user ID, roles, scopes) in auth tokens",
      "Understand JWT structure when learning about authentication systems",
    ],
  },
  "markdown-converter": {
    whatIs: "A Markdown Converter renders Markdown text into a live HTML preview and lets you export it as a formatted PDF, Word DOCX, or raw HTML. It supports standard Markdown syntax — headings, bold, italic, tables, code blocks, and links.",
    howToUse: [
      "Type or paste Markdown text in the left editor panel",
      "The right panel shows a live HTML preview that updates as you type",
      "Click 'Export PDF' to download a formatted PDF of your document",
      "Click 'Export DOCX' to download a Word-compatible document",
    ],
    example: "Write a report in Markdown with # for headings, **bold** for key terms, and | tables | for data. Export to PDF for sharing with non-technical stakeholders, or to DOCX for editing in Microsoft Word.",
    whyUse: [
      "Write documentation, README files, or reports in Markdown and export to any format",
      "Convert Markdown blog posts to HTML for direct use in CMS platforms",
      "Create professional PDFs from plain text without a word processor",
      "Write once, export to PDF, DOCX, and HTML for different audiences",
    ],
  },
};

