import { PageLayout } from "@/components/layout/PageLayout";

export default function Disclaimer() {
  return (
    <PageLayout>
      <div className="mx-auto max-w-3xl px-4 sm:px-6 py-16 mb-16">
        <h1 className="text-4xl font-display font-bold mb-8 tracking-tight">Disclaimer</h1>

        <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground">
          <p>
            The information and calculators provided on ToolsKit are for general informational
            and educational purposes only.
          </p>

          <h2 className="text-foreground font-display">Financial Calculators (SIP, EMI, GST)</h2>
          <p>
            The results generated by our financial calculators (including but not limited to
            the SIP Calculator, EMI Calculator, and GST Calculator) are estimates based on the
            inputs you provide and standard mathematical formulas.
          </p>
          <p>
            They do NOT constitute professional financial advice, tax advice, or a guarantee
            of returns. Actual results may vary due to factors such as:
          </p>
          <ul>
            <li>Market fluctuations affecting mutual fund returns</li>
            <li>Changes in interest rates by lending institutions</li>
            <li>Additional fees, taxes, or charges applied by banks</li>
            <li>Rounding differences in calculation methods</li>
          </ul>
          <p>
            Always consult with a qualified financial advisor, tax professional, or your bank
            before making any significant financial decisions or investments.
          </p>

          <h2 className="text-foreground font-display">General Utilities</h2>
          <p>
            While we strive for 100% accuracy in all our tools, software bugs can occur.
            ToolsKit provides these utilities "as is" without warranty of any kind. We are not
            liable for any damages, data loss, or errors resulting from the use of our text
            converters, JSON formatters, or other utilities.
          </p>
        </div>
      </div>
    </PageLayout>
  );
}
